version: '3.9'

services:
  master:
    image: redis:latest
    container_name: redis-cluster_master_1
    ports:
      - "6379:6379"

  slave:
    image: redis:latest
    container_name: redis-cluster_slave_1
    command: redis-server --slaveof redis-cluster_master_1 6379
    depends_on:
      - master

  sentinel:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: redis-cluster_sentinel_1
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    depends_on:
      - master
      - slave
